version: "3"

services:
  migrations:
    image: django-price-finder
    command: python3 manage.py migrate
    volumes:
    - ./apps:/app

  web:
    image: django-price-finder
    entrypoint: python3 manage.py runserver
    command: 0.0.0.0:8000
    ports:
    - "8010:8000"
    volumes:
    - ./apps:/app
    depends_on:
      - migrations